name: smart_monitor
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.31.11
  permission_handler: ^12.0.0+1
  location: ^4.4.0  
  logging: ^1.0.2 
  font_awesome_flutter: ^10.5.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
